version: '3'

services:
  app:
    container_name: developer.app
    image: developer.app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:80"
    expose:
      - 6060
    volumes:
      - ./src/appsettings-compose.json:/app/bin/appsettings.json
    networks:
      - internal
    depends_on:
      - db

  db:
    container_name: developer.db
    image: mcr.microsoft.com/mssql/server:2019-latest    
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pass123*"
      ACCEPT_EULA: "Y"       
    networks:
      - internal
   
networks: 
    internal:
        driver: bridge